### ISSUE TITLE
Monitoring vs PVT

### ISSUE THREAD

**Issue by KingerNL** [acebrianjuan/gnss-sdr-pvt-monitoring-client#2]
Hi there,

I have been using the documentation gnss-sdr gave for monitoring channels: [Monitoring the internal status of the software receiver](https://gnss-sdr.org/docs/tutorials/monitoring-software-receiver-internal-status/).

I want to merge both the Monitoring and PVT to get all the data. 
Now I'm able to run both programs separate, but when I add the code into the other file, I get an error. The problem is the "read_monitor_pvt" which differs from the Gnss_Synchro_Udp_Source from their code:

``char buff[2000]{};  // Buffer for storing the received data. ``

    // This call will block until one or more bytes of data has been received.
    int bytes = socket.receive(boost::asio::buffer(buff));

    try
        {
            // Deserialize Monitor_Pvt objects from the binary archive.
            std::string archive_data(&buff[0], bytes);
            std::istringstream archive_stream(archive_data);
            boost::archive::binary_iarchive archive(archive_stream);
            archive >> monitor_pvt;
        }
    catch (std::exception& e)
        {
            return false;
        }`

and what they have:
``   char buff[1500];  // Buffer for storing the received data. ``

    // This call will block until one or more bytes of data has been received.
    int bytes = socket.receive(boost::asio::buffer(buff));

    std::string data(&buff[0], bytes);
    // Deserialize a stock of Gnss_Synchro objects from the binary string.
    return stocks.ParseFromString(data);`

I got an error in the binary_iarchive() function, do you knw what it does? And if I need to edit the their CMakeLists.txt file in any way to get rid of this error? Thanks.

**Comment by voldrfr1** [comment]
Hello @KingerNL, I was doing exactly the same thing and run into the same problem - the program would crash at binary_iarchive function call. However, I found out the problem can be tracked to the configuration of GNSS SDR, more specifically with the line "Monitor.enable_protobuf=true". Removing or setting this to 'false' appears to make the monitor and PVT monitor run together. Both monitors seems to be giving correct results, which makes me wonder why is there the line in the tutorial in the first place.

Does that help you? Or did you find another solution?
BTW it could be a good idea to run each monitor in a separate thread in order not to block each other.

EDIT:
Actually, setting Monitor.enable_protobuf to either true or false breaks the monitor, but ommiting the line alltogether makes it work. I have no explanation for this behaviour.

**Comment by KingerNL** [comment]
> Hello @KingerNL, I was doing exactly the same thing and run into the same problem - the program would crash at binary_iarchive function call. However, I found out the problem can be tracked to the configuration of GNSS SDR, more specifically with the line "Monitor.enable_protobuf=true". Removing or setting this to 'false' appears to make the monitor and PVT monitor run together. Both monitors seems to be giving correct results, which makes me wonder why is there the line in the tutorial in the first place.
> 
> 
> 
> Does that help you? Or did you find another solution?
> 
> BTW it could be a good idea to run each monitor in a separate thread in order not to block each other.
> 
> 

Thanks for your help, I've since been able to fix this issue, and are already running them in separate tracks. 

Because it was quite a time ago and currently don't have my work laptop, I can't easily check what I've changed. But thanks for the suggestion.

Also for people who want to display the data received. Make sure the reading and writing is secure for undefined behavior with posix locks.
